### PR TITLE
FullWidth and Padding params added

### PR DESCRIPTION
**Pull request by JEuler**

### CODE REVIEW

**Comment by AlexV525** [comment]
Thanks for these further commits.

I was wondering the feature that you implemented, since I can't tell the demand that this PR is going to fix.
Besides, there are some format issues that need some tweak, but let's not figure them out until the main idea of this PR is clear.

**Comment by JEuler** [comment]
This an easy option to make toast fullscreen, it wasn't working in the base version (long time ago) and also, I have added toast margin to add optional margin for toast.

**Comment by AlexV525** [comment]
SGTM. How about we implement this by using the constraints or width properties? For example, `width: fullWidth ? double.maxFinite : null` . Let me know whether you'll agree with this.

**Comment by AlexV525** [comment]
Also considering the structure of the exisiting code, I'd suggest to use constraints and make it public instead of a simple flag, because once we support full width, soon there will be new requests for half of the max width.

**Comment by JEuler** [comment]
Yeah, I think it is cool. Still on vacationing mode, so if you can rework it as you see, it would be cool. I will work on that later :)

**Comment by AlexV525** [comment]
> Yeah, I think it is cool. Still on vacationing mode, so if you can rework it as you see, it would be cool. I will work on that later :)

Cool, I'll submit another PR and let you try if it works.

**Comment by AlexV525** [comment]
See #84 .

**Comment by JEuler** [comment]
Looks cool!

**Pull request closed without merging**
